homework6: main.o weightedGraph.o
	g++ -o homework6 main.o weightedGraph.o

main.o: main.cpp weightedGraph.cpp
	g++ -c main.cpp

weightedGraph.o: weightedGraph.h weightedGraph.cpp
	g++ -c weightedGraph.cpp