homework5: driver.o binarySearchTree.o
	g++ -o homework5 driver.o binarySearchTree.o

driver.o: driver.cpp binarySearchTree.h
	g++ -c driver.cpp

binarySearchTree.o: binarySearchTree.cpp binarySearchTree.h
	g++ -c binarySearchTree.cpp